In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../dataset/emails.csv", encoding="latin-1")

print("Dataset Loaded Successfully!")

Dataset Loaded Successfully!

In [3]:
df = df[['v1', 'v2']]

df.columns = ['label', 'message']

df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.tail()

     label                                            message
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [6]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 5572
Columns : 2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [8]:
df.isnull().sum()

label      0
message    0
dtype: int64

In [9]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 403

In [10]:
df = df.drop_duplicates()

print(df.shape)

(5169, 2)

In [11]:
df["label"].value_counts()

label
ham     4516
spam     653
Name: count, dtype: int64

In [12]:
(df["label"].value_counts(normalize=True)*100).round(2)

label
ham     87.37
spam    12.63
Name: proportion, dtype: float64

In [13]:
df.sample(5)

     label                                            message
5010  spam  You have WON a guaranteed å£1000 cash or a å£2...
303    ham                           He is a womdarfull actor
3603   ham          Hey morning what you come to ask:-) pa...
5158   ham  I will come with karnan car. Please wait till ...
2087   ham                                      \alright babe

In [14]:
print("="*50)
print("EMAIL SPAM DETECTION PROJECT")
print("="*50)

print("Rows :",df.shape[0])
print("Columns :",df.shape[1])
print("Missing Values :",df.isnull().sum().sum())
print("Duplicate Rows :",df.duplicated().sum())

print("\nLabel Distribution")
print(df["label"].value_counts())

print("="*50)

==================================================
EMAIL SPAM DETECTION PROJECT
==================================================
Rows : 5169
Columns : 2
Missing Values : 0
Duplicate Rows : 0

Label Distribution
label
ham     4516
spam     653
Name: count, dtype: int64
==================================================